apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: alpine
spec:
  containers:
  - name: alpine-container-1
    image: alpine:3.12.0
    command: ["sh", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: shared-volume
      mountPath: /etc/a
  - name: alpine-container-2
    image: alpine:3.12.0
    command: ["sh", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: shared-volume
      mountPath: /etc/b
  volumes:
  - name: shared-volume
    emptyDir: {}
